# Esercizio 1

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [1]:
import numpy as np
a=np.array([1.2, 5.4, 6, 1.59])
b=np.array([5.2, 1.2, 1.5, 2])

print(np.sqrt(a))
print(np.exp(a/2))
print(a+b)
print(a*b)
print(np.arange(0,30.1,0.5))
print(np.linspace(1,2,100))
print(np.concatenate((np.linspace(10,20,6,dtype=int),np.linspace(20,10,6,dtype=int))).reshape((2,6)))
print(a @ b)
A=np.concatenate((a,b)).reshape((2,4))
print(A)
print(a @ b)
y=A@b
print(y)
D=np.diag(a)
print(D)

[1.09544512 2.32379001 2.44948974 1.26095202]
[ 1.8221188  14.87973172 20.08553692  2.214441  ]
[6.4  6.6  7.5  3.59]
[6.24 6.48 9.   3.18]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30. ]
[1.         1.01010101 1.02020202 1.03030303 1.04040404 1.05050505
 1.06060606 1.07070707 1.08080808 1.09090909 1.1010101  1.11111111
 1.12121212 1.13131313 1.14141414 1.15151515 1.16161616 1.17171717
 1.18181818 1.19191919 1.2020202  1.21212121 1.22222222 1.23232323
 1.24242424 1.25252525 1.26262626 1.27272727 1.28282828 1.29292929
 1.3030303  1.31313131 1.32323232 1.33333333 1.34343434 1.35353535
 1.36363636 1.37373737 1.38383838 1.39393939 1.4040404  1.41414141
 1.42424242 1.43434343 1.44444444 1.45454545 1.46464646 1.47474747
 1.48484848 1

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [151]:
import numpy as np
A = np.full((3,4),2)
A[:,3] = 3
print(A)
B = np.diag([2,2,2])
for i in range(1,11):
    B = np.hstack((B,np.full((3,1),i)))
print(B)
C = np.eye(5,5).astype(int) * 2 + np.eye(5,5,1).astype(int) * -1 + np.eye(5,5,-1).astype(int) * -1
print(a+b+c)
D = np.zeros((6,4)).astype(int)
D[0:2,0:2]=2
D[0:2,2:4]=3
D[4:6,2:4]=np.diag([5,5])
print(D)

[[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]]
[[ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]]
[[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]
[[2 2 3 3]
 [2 2 3 3]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 5 0]
 [0 0 0 5]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [3]:
import numpy as np
def odds(n):
    sum = 0
    for i in range(1,n*2,2):
        sum += i
    return sum
print(odds(3))

9


In [4]:
def odds(n):
    return n**2
print(odds(3))

9


In [5]:
import numpy as np
def odds(n):
    return np.sum(np.arange(1,n*2,2))
print(odds(3))

9


# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

Ricordiamo la formula per generare i i numeri di Fibonacci:

$$F_0=1$$
$$F_1=1$$
$$F_n = F_{n-1} + F_{n-2}, \quad n=2,...$$

In [79]:
import time
def fibonacci(n):
    curr = 1
    prev = 1
    for i in range(2,n+1):
        prev+=curr
        prev,curr=curr,prev
    return curr     


TIME=1000_000
start = int(time.perf_counter() * TIME)
print(fibonacci(35))
end = int(time.perf_counter() * TIME)
print("tempo impiegato: ",(end - start )/ TIME)

14930352
tempo impiegato:  0.000175


In [78]:
import time
def fibonacci(n):
    if n < 2:
        return 1
    return fibonacci(n-1) + fibonacci(n-2)

TIME=1000_000
start = int(time.perf_counter() * TIME)
print(fibonacci(35))
end = int(time.perf_counter() * TIME)
print("tempo impiegato: ",(end - start )/ TIME)


14930352
tempo impiegato:  2.096933
